# Outdated and not in use

# For Use on Github Pages
name: Update Exam Simulator on Githib Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu
    steps:
      # Checkout DECA-ExamSimulator repo (this one)
      - uses: actions/checkout@v2

      # Clone DECA-ExamSimulator repo again (if needed — or just use current files)
      - name: Clone DECA-ExamSimulator
        uses: actions/checkout@v4
        with:
          repository: JaxGM/DECA-ExamSimulator
          token: ${{ secrets.API_TOKEN_GITHUB }}
          path: deca-exam-simulator

      # Push DECA-ExamSimulator to your Pages repo
      - name: Push DECA-ExamSimulator to another repository
        id: push_exam_simulator
        uses: cpina/github-action-push-to-another-repository@main
        if: github.ref == 'refs/heads/main'
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: ./deca-exam-simulator/
          destination-github-username: 'JaxGM'
          destination-repository-name: 'JaxGM.github.io'
          user-email: flume_prowl_0n@icloud.com
          target-branch: main
          target-directory: ./DECA-ExamSimulator/
